# Generated by Django 4.2.23 on 2025-06-21 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('customer_type', models.CharField(choices=[('RETAIL', '零售'), ('WHOLESALE', '批发'), ('VIP', 'VIP客户')], default='RETAIL', max_length=20, verbose_name='客户类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='产品编号')),
                ('category', models.CharField(choices=[('RM', '原材料'), ('FP', '成品'), ('SF', '办公用品')], max_length=2, verbose_name='分类')),
                ('unit', models.CharField(choices=[('PCS', '件'), ('KG', '千克'), ('M', '米'), ('BOX', '箱')], default='PCS', max_length=5, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='当前库存')),
                ('alert_threshold', models.PositiveIntegerField(default=10, verbose_name='库存预警值')),
                ('location', models.CharField(blank=True, help_text='仓储位置', max_length=20, verbose_name='库位')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['code'],
                'permissions': [('export_product', '导出产品数据'), ('manage_product', '管理产品库存')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('rating', models.PositiveIntegerField(default=3, help_text='1-5分，5分为最佳', verbose_name='评级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='销售单价')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='折扣率')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('shipped', '已发货'), ('canceled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('shipping_address', models.TextField(blank=True, verbose_name='配送地址')),
                ('expected_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='要求交付日期')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='客户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='采购单价')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='总金额')),
                ('expected_date', models.DateField(default=django.utils.timezone.now, verbose_name='预计到货日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('canceled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='产品')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='供应商')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', '采购入库'), ('OUT', '销售出库'), ('ADJ', '库存调整'), ('TRF', '仓库转移')], max_length=3, verbose_name='类型')),
                ('quantity', models.IntegerField(verbose_name='变动数量')),
                ('reference', models.CharField(max_length=50, verbose_name='关联单据')),
                ('operator', models.CharField(max_length=50, verbose_name='操作员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('location_from', models.CharField(blank=True, max_length=20, verbose_name='源库位')),
                ('location_to', models.CharField(blank=True, max_length=20, verbose_name='目标库位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
